id: A47F54B12
title: Guru Yoga of Jetsün Shepa Dorje
type: translation
pechas:
- IBEBADCA1
- I69E82664
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:02:07.015830
  last_modified_at: 2023-01-04 13:02:07.015837
  collections:
  - Milarepa Series
  - Works of Tibetan Masters
alignment_to_base:
  IBEBADCA1/8CCB: 444C
  I69E82664/7934: 444C
